"""
Copyright (C) J Leadbetter <j@jleadbetter.com>
Affero GPL v3
"""

from common.models.documents import DocumentDB
from common.ports.documents import DocumentPort
from common.utils.languages import LanguageCode

from ..models.documents import Document


class DocumentDjangoORMAdapter(DocumentPort):
    """
    Converts documents from the Django ORM into UI objects
    """

    def read_all_for_user(
        self,
        user_id: str,  # UUID
        language_code: Optional[LanguageCode] = None,
    ) -> List[DocumentDB]:
        """
        Find documents for the specified user.

        :user_id: User id to search in the database.
        :language_code: optional filter to return documents for a specific
            language. If not specified, returns all documents.

        :return: List of documents
        """

        documents = Document.objects.filter(user__id=user_id)
        if language_code:
            documents = documents.filter(language_code=language_code)

        document_dbs = [
            DocumentDB(
                id=doc.id,
                user_id=doc.user.id,
                display_name=doc.display_name,
                language_code=language_code,
                doc_file=do

    id: Optional[str] = None  # UUID. Generated by the database.
    user_id: str  # UUID
    display_name: str
    language_code: LanguageCode
    doc_file: str  # Relative path in file system
    sentences: List[SentenceDBMinimal]
    translations: Optional[List[DocumentDBMinimal]] = None

    display_name = models.CharField(
        max_length=255,
        help_text=_('How the document will be named in the UI'),
    )
    language_code = models.CharField(
        max_length=8,
        choices=language_choices(),
        help_text=_('Language that the sentence belongs to'),
    )
    doc_file = models.FileField(
        upload_to=document_directory_path,
        unique=True,
    )
