"""
Copyright (C) J Leadbetter <j@jleadbetter.com>
Affero GPL v3
"""

from typing import List, Optional

from pydantic import BaseModel

from .base import HashableMixin
from .sentences import SentenceDB, SentenceDBMinimal, SentenceUI
from .users import UserDB, UserUI
from ..utils.languages import LanguageCode


class DocumentDBMinimal(HashableMixin, BaseModel):
    """
    Minimal representation of a document in the database
    """

    id: str = None
    user_id: str  # UUID.
    display_name: str
    language_code: LanguageCode


class DocumentDB(HashableMixin, BaseModel):
    """
    Representation of a document to be stored in the database
    """

    id: Optional[str] = None  # UUID. Generated by the database.
    user_id: str  # UUID
    display_name: str
    language_code: LanguageCode
    doc_file: str  # Relative path in file system
    sentences: List[SentenceDBMinimal]
    translations: Optional[List[DocumentDBMinimal]] = None

    @property
    def unique_fields(self):
        return ['user_id', 'display_name', 'language_code']


class DocumentUIMinimal(HashableMixin, BaseModel):
    """
    Bare minimum display of documents in the UI
    Excludes Sentences and Words
    """

    id: str  # UUID
    user: UserUI
    displayName: str
    languageCode: LanguageCode

    @classmethod
    def from_db(
        cls,
        document: DocumentDB,
        user: UserDB,
    ) -> 'DocumentUIMinimal':
        """
        Convert a DocumentDB into a DocumentUIMinimal
        """

        user_ui = UserUI.from_db(user)
        document_ui = cls(
            id=document.id,
            user=user_ui,
            displayName=document.display_name,
            languageCode=document.language_code,
        )
        return document_ui


class DocumentUI(HashableMixin, BaseModel):
    """
    All information needed to display a Document and its Sentences/Words.
    Includes user tracking for learned words
    """

    id: str  # UUID
    user: UserUI
    displayName: str
    languageCode: LanguageCode
    sentences: List[SentenceUI]
