"""
Copyright (C) J Leadbetter <j@jleadbetter.com>
Affero GPL v3
"""

from typing import List, Optional

from pydantic import BaseModel

from .sentences import SentenceDB, SentenceUI
from .users import UserUI


class DocumentDB(BaseModel):
    """
    Representation of a document to be stored in the database
    """

    id: Optional[str] = None  # UUID. Generated by the database.
    user_id: str  # UUID. Taken from DocumentUI.user.id
    display_name: str
    language_code: str  # See common.utils.languages.language_choices
    doc_file: str  # Relative path in file system
    sentences: List[SentenceDB]


class DocumentUIMinimal(BaseModel):
    """
    Bare minimum display of documents in the UI
    Excludes Sentences and Words
    """

    id: str  # UUID
    user: UserUI
    displayName: str
    languageCode: str  # See common.utils.languages.language_choices


class DocumentUI(BaseModel):
    """
    All information needed to display a Document and its Sentences/Words.
    Includes user tracking for learned words
    """

    id: str  # UUID
    user: UserUI
    displayName: str
    languageCode: str  # See common.utils.languages.language_choices
    sentences: List[SentenceUI]
