"""
Copyright (C) J Leadbetter <j@jleadbetter.com>
Affero GPL v3
"""

from typing import List, Optional

from pydantic import BaseModel

from .conjugations import ConjugationUI
from .users import UserUI


class SentenceDB(BaseModel):
    """
    Representation of a sentence to be stored in the database
    """

    id = Optional[str] = None  # UUID. Generated by the database.
    user_id: str  # UUID. Taken from DocumentUI.user.id
    language_code: str  # See common.utils.languages.language_choices
    text: str
    audio_file: Optional[str] = None  # Relative path in the file system
    translations: Optional[List[SentenceDB]] = None
    order: int  # Relative to the DocumentDB
    conjugations: List[ConjugationDB]


class SentenceUIMinimal(BaseModel):
    """
    Minimal representation of a sentence in the UI.
    Does not include individual words or user tracking.
    """

    id: str  # UUID
    languageCode: str  # See common.utils.languages.language_choices
    text: str
    audioFile: Optional[str] = None  # Relative path from the UI's perspective


class SentenceUI(BaseModel):
    """
    Full representation of a sentence in the UI.
    Includes words with tracking information.
    """

    id: str  # UUID
    user: UserUI
    languageCode: str  # See common.utils.languages.language_choices
    text: str
    audioFile: Optional[str] = None  # Relative path from the UI's perspective
    translations: OptionalList[SentenceUIMinimal] = None
    order: int  # Relative to the DocumentUI
    conjugations: List[Conjugations]
