# Generated by Django 5.1.5 on 2025-01-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conjugation',
            name='emphasis',
            field=models.CharField(blank=True, choices=[('stressed', 'Stressed'), ('unstressed', 'Unstressed')], max_length=40, null=True),
        ),
    ]
